/*

*/
CISlider2(['slider0.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from ',160,120]);
CISlider2(['slider1.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from ',160,120]);
CISlider2(['slider2.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from ',160,120]);
CISlider2(['slider3.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from ',160,120]);
CISlider2(['slider4.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from ',160,120]);
CISlider2(['slider5.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from ',160,120]);
CISlider2(['slider6.jpg','','_self','This script was generated by JavaScript FadeIn SlideShow from ',160,120]);
function CISlider2(ipa){
if(!(window.Slider2cfg)){eval('window.Slider2cfg=new Array();');};
Slider2cfg[Slider2cfg.length]=ipa;};
function InitSlider2(){
if (!window.bkag){setTimeout('InitSlider2()',350);return;};
new bPaf('SlideShow1','FadeInSlideShow1_div',160,120,'FFFFFF',0,30,Slider2cfg,4);
};
InitSlider2();
